import 'package:aplicativo_maria/bloc/message_bloc.dart';
import 'package:aplicativo_maria/data/sqflite_data.dart';
import 'package:aplicativo_maria/injections/get_injections.dart';
import 'package:aplicativo_maria/models/message_model.dart';
import 'package:aplicativo_maria/themes/theme.dart';
import 'package:aplicativo_maria/views/page_view.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:uuid/uuid.dart';

void main() {
  runApp(const MyApp());
  setup();
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Meu Amor Infinito por Maria', description: 'Maria, meu amor por você transcende as barreiras do tempo e do espaço. Cada dia que passa, sinto que nossa conexão se fortalece e se aprofunda. Seu sorriso ilumina meus dias e suas palavras aquecem meu coração. Eu me sinto abençoado por ter você ao meu lado, compartilhando cada momento de alegria e superando juntos qualquer dificuldade. Você é minha inspiração e a razão de eu acreditar em um amor eterno. Nada no mundo pode medir o quanto eu te amo, Maria. Você é e sempre será meu amor infinito.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Razão do Meu Sorriso: Maria', description: 'Maria, você é a razão pela qual eu acordo todos os dias com um sorriso no rosto. Sua presença traz luz e felicidade à minha vida, transformando os dias mais sombrios em momentos de pura alegria. Cada gesto seu, cada palavra doce, faz meu coração bater mais forte. Quando estou ao seu lado, sinto que tudo é possível, e minha alma se enche de esperança e gratidão. Você tem a capacidade única de transformar a rotina em algo extraordinário. Sou eternamente grato por você ser a razão do meu sorriso. Te amo imensamente, Maria.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Doce Paixão', description: 'Maria, você é a chama que aquece meu coração e a doçura que dá sabor aos meus dias. Sua paixão pela vida e por tudo que faz me inspira a ser uma pessoa melhor. Quando estamos juntos, sinto uma energia vibrante que me envolve e me faz querer estar ao seu lado para sempre. Seu amor é uma melodia suave que toca minha alma e me faz sonhar acordado. Com você, cada momento é uma aventura emocionante, cheia de descobertas e emoções intensas. Minha doce paixão, você é o amor da minha vida. Te amo com toda a intensidade do meu ser.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Você é Tudo pra Mim, Maria', description: 'Maria, você é o centro do meu universo e a força que me impulsiona a seguir em frente. Cada pensamento, cada sonho, cada plano inclui você, pois sem você nada faria sentido. Seu amor é o alicerce sobre o qual construí minha vida, e seu sorriso é o sol que ilumina meus dias. Em seus olhos encontro paz, em seu abraço, conforto, e em suas palavras, encorajamento. Você é minha amiga, minha confidente, minha amante, minha inspiração. Tudo o que sou e tudo o que tenho é para você e por você. Amo você mais do que palavras podem expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Meu Amor Eterno', description: 'Maria, desde o momento em que te conheci, soube que nosso amor seria eterno. Você trouxe uma alegria indescritível à minha vida, e juntos construímos uma história repleta de momentos inesquecíveis. Seu carinho, sua compreensão e sua lealdade me fizeram acreditar no poder do amor verdadeiro. Não importa o que o futuro nos reserve, sei que nosso amor resistirá ao teste do tempo. Você é meu refúgio seguro e minha felicidade constante. Amo você mais a cada dia, e sei que nosso amor durará para sempre. Você é e sempre será meu amor eterno, Maria.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Para a Mulher da Minha Vida: Maria', description: 'Maria, você é a mulher dos meus sonhos e a realidade mais bela que poderia desejar. Desde que você entrou na minha vida, tudo ganhou um novo sentido. Sua força, sua delicadeza e sua sabedoria são apenas algumas das qualidades que admiro em você. Cada dia ao seu lado é um presente que aprecio com todo o meu coração. Você me ensina a ser uma pessoa melhor e a ver o mundo de uma forma mais positiva e amorosa. Sou grato por cada momento que compartilhamos e por cada lembrança que criamos juntos. Para você, a mulher da minha vida, dedico todo o meu amor e devoção.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Amar Você, Maria, é Fácil', description: 'Amar você, Maria, é a coisa mais natural e maravilhosa que já experimentei. Sua beleza, tanto interior quanto exterior, me cativa e me inspira diariamente. Você tem uma capacidade incrível de trazer paz e alegria aos meus dias, mesmo nos momentos mais desafiadores. Sua risada é música para os meus ouvidos, e seu toque é o conforto que meu coração sempre procura. Estar com você é um privilégio que aprecio imensamente. Amar você é fácil porque você é extraordinária em todos os sentidos. Cada momento ao seu lado é um lembrete do quanto sou sortudo por ter você na minha vida.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Cada Dia Mais Apaixonado por Maria', description: 'Maria, a cada dia que passa, meu amor por você cresce e se fortalece. Cada nova experiência que compartilhamos, cada desafio que enfrentamos juntos, me faz admirar e amar você ainda mais. Sua resiliência, bondade e paixão pela vida me inspiram a ser uma pessoa melhor. O jeito como você se entrega ao nosso amor, com tanto carinho e dedicação, me faz sentir o homem mais sortudo do mundo. Não importa quantos anos passem, sei que continuarei me apaixonando por você mais e mais. Você é a mulher da minha vida, e meu amor por você só aumenta com o tempo.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Inspiração Diária', description: 'Maria, você é a luz que guia meus dias e a inspiração que alimenta minha alma. Cada vez que olho para você, sinto uma onda de gratidão e amor inundar meu coração. Sua capacidade de enfrentar os desafios com graça e determinação me motiva a fazer o mesmo. Seu sorriso, sua risada e sua presença constante me lembram de que a vida é bela e vale a pena ser vivida com intensidade. Você me inspira a ser uma pessoa melhor, a lutar pelos meus sonhos e a amar sem reservas. Maria, você é a razão pela qual eu me esforço para ser o melhor que posso ser a cada dia.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Com Você, Maria, Sou Completo', description: 'Maria, você trouxe um sentido de completude à minha vida que eu nunca imaginei ser possível. Antes de você, havia um vazio que eu não sabia como preencher. Agora, cada momento ao seu lado me faz sentir pleno e realizado. Seu amor, sua compreensão e seu apoio incondicional são tudo o que eu preciso para ser feliz. Você me faz sentir amado e valorizado de uma maneira que nunca experimentei antes. Juntos, somos mais fortes e capazes de conquistar qualquer coisa. Com você, Maria, sou verdadeiramente completo e não desejo mais nada além de estar ao seu lado para sempre.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Você é Meu Lar', description: 'Maria, ao seu lado encontrei um lugar de conforto e segurança que sempre procurei. Você é meu refúgio, onde posso ser eu mesmo sem medo de julgamento. Seu abraço é onde encontro paz, e suas palavras são o alento que meu coração precisa. Com você, qualquer lugar se torna um lar, cheio de amor e felicidade. Não importa onde estejamos, enquanto estivermos juntos, estarei em casa. Seu amor me acolhe e me faz sentir protegido e amado. Maria, você é meu lar, meu porto seguro e o amor da minha vida.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'O Brilho dos Meus Olhos: Maria', description: 'Maria, você é a estrela que ilumina minha vida e o brilho dos meus olhos. Cada vez que te vejo, sinto uma alegria inexplicável tomar conta de mim. Seu sorriso é como um raio de sol que dissipa qualquer escuridão. Quando estamos juntos, tudo ao meu redor parece mais bonito e cheio de vida. Você traz cor aos meus dias e esperança ao meu coração. Seu amor é o combustível que me faz seguir em frente, sempre com um brilho nos olhos. Maria, você é minha luz, minha inspiração e a razão pela qual meus olhos brilham de felicidade.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Meu Amor Verdadeiro', description: 'Maria, você é a personificação do amor verdadeiro em minha vida. Desde que nos encontramos, senti que nossa conexão era única e especial. Seu amor é puro, sincero e incondicional, algo que eu nunca havia experimentado antes. Você me aceita como sou e me faz querer ser uma pessoa melhor a cada dia. Cada momento ao seu lado é uma prova de que o amor verdadeiro existe e é capaz de transformar vidas. Amo você com todo meu coração e sei que nosso amor é eterno e inabalável. Maria, você é meu amor verdadeiro e sempre será.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Para Sempre ao Seu Lado, Maria', description: 'Maria, prometo estar ao seu lado para sempre, não importa o que aconteça. Nosso amor é minha maior prioridade e farei tudo para protegê-lo e fortalecê-lo. Você trouxe tanta alegria e significado à minha vida que não consigo imaginar um futuro sem você. Cada dia ao seu lado é uma bênção, e cada desafio que enfrentamos juntos nos torna mais fortes. Vou amar, cuidar e apoiar você em todos os momentos, bons ou ruins. Maria, meu compromisso com você é eterno, e sempre estarei ao seu lado, amando você com todo meu coração.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Minha Deusa, Minha Maria', description: 'Maria, você é a deusa que governa meu coração e a mulher que venero todos os dias. Sua beleza, graça e sabedoria me deixam em constante admiração. Cada gesto seu é uma obra de arte, e cada palavra, uma poesia que encanta minha alma. Você tem uma força interior que me inspira e uma bondade que me comove profundamente. Estar ao seu lado é um privilégio que aprecio com toda a minha alma. Maria, você é minha deusa, minha musa e a razão pela qual acredito no poder do amor. Amo você de uma maneira que palavras não conseguem descrever.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Meu Coração Bate por Você', description: 'Maria, cada batida do meu coração é um testemunho do amor que sinto por você. Desde o momento em que te conheci, senti que meu coração pertencia a você. Sua presença enche minha vida de alegria e propósito, e seu amor é a força que mantém meu coração batendo com tanto vigor. Cada dia ao seu lado é uma prova de que nascemos um para o outro. Quando estou com você, sinto que tudo é possível e que o amor verdadeiro realmente existe. Maria, meu coração bate por você, hoje e sempre.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Todo Meu Amor é Seu, Maria', description: 'Maria, dedico todo o meu amor a você, a mulher mais incrível que já conheci. Você é a razão pela qual meu coração transborda de felicidade e gratidão. Seu amor me completa de uma maneira que nunca pensei ser possível. Cada gesto seu, cada palavra de carinho, me faz te amar ainda mais. Você é minha melhor amiga, minha confidente e minha eterna companheira. Não há nada que eu não faria por você, pois todo o meu amor é seu. Maria, você é minha vida, meu amor e minha maior felicidade.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Musa Inspiradora', description: 'Maria, você é a musa que inspira meus sonhos e minhas realizações. Sua beleza, tanto interior quanto exterior, me motiva a criar, a sonhar e a buscar sempre o melhor. Cada momento ao seu lado é uma fonte de inspiração que enriquece minha vida. Você tem uma capacidade única de transformar o ordinário em extraordinário, e sua paixão pela vida me contagia. Sua presença me encoraja a ser mais criativo e a ver o mundo com novos olhos. Maria, você é minha musa inspiradora, e meu amor por você é a maior obra de arte que já criei.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Dona do Meu Coração: Maria', description: 'Maria, você é e sempre será a dona do meu coração. Desde o momento em que nos conhecemos, senti que meu coração estava destinado a pertencer a você. Seu amor, carinho e compreensão são tudo o que eu sempre sonhei. Você tem o poder de acalmar minhas tempestades e iluminar meus dias mais sombrios. Cada batida do meu coração é um lembrete constante de quanto te amo. Você é minha alma gêmea, minha companheira de vida e a única que possui a chave do meu coração. Maria, você é a dona do meu coração, hoje e para sempre.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Meu Refúgio de Paz', description: 'Maria, em você encontrei o refúgio de paz que sempre procurei. Sua presença me traz uma serenidade que nada mais consegue proporcionar. Quando estou ao seu lado, sinto que todos os problemas do mundo desaparecem e tudo fica mais claro e simples. Seu amor é como um abrigo seguro onde posso descansar e recuperar minhas forças. Você é meu porto seguro, minha tranquilidade em meio ao caos. Com você, encontrei a paz que meu coração tanto ansiava. Maria, você é meu refúgio, meu conforto e minha paz.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Você e Eu, Maria, para Sempre', description: 'Maria, nosso amor é uma promessa de eternidade. Desde o momento em que nos encontramos, soube que queria passar o resto da minha vida ao seu lado. Cada dia juntos fortalece nosso vínculo e me faz acreditar ainda mais no nosso "para sempre". Enfrentamos desafios e celebramos vitórias, sempre de mãos dadas. Você é minha parceira, minha amiga e minha confidente. Juntos, somos invencíveis e capazes de enfrentar qualquer coisa que a vida nos apresente. Maria, você e eu, para sempre, é a única realidade que desejo. Amo você eternamente.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Você é Minha Melodia', description: 'Maria, você é a melodia que dá ritmo e harmonia à minha vida. Cada momento ao seu lado é como uma canção doce que enche meu coração de alegria e paz. Seu amor é a música que embala meus dias e acalma minhas noites. Com você, cada experiência se torna uma sinfonia de emoções que nunca canso de ouvir. Seu riso é a nota mais alta da minha felicidade, e seu abraço, a melodia que me conforta. Maria, você é a composição perfeita que dá sentido à minha existência. Amo você mais do que qualquer canção pode expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Magia de Amar Maria', description: 'Maria, amar você é uma experiência mágica que transforma minha vida todos os dias. Seu amor tem o poder de transformar os momentos mais simples em memórias inesquecíveis. Quando estou ao seu lado, sinto que tudo é possível e que a vida é cheia de maravilhas. Sua presença traz uma alegria indescritível e uma paz profunda ao meu coração. Você é a magia que colore meus dias e enche meu coração de esperança. Amar você é um encantamento que me faz acreditar no impossível. Maria, você é a magia que faz minha vida brilhar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Meu Tesouro Precioso', description: 'Maria, você é o tesouro mais precioso que eu poderia encontrar. Sua presença enriquece minha vida de uma maneira que nada mais pode fazer. Cada momento com você é uma joia rara que guardo com todo o carinho. Seu amor, sua bondade e sua beleza são tesouros que valorizo profundamente. Você trouxe um brilho especial aos meus dias e uma felicidade que não tem preço. Com você, sinto que possuo a riqueza mais valiosa do mundo. Maria, você é meu tesouro, meu amor e minha maior alegria. Amo você infinitamente.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Você é Minha Vida, Maria', description: 'Maria, você é a essência da minha vida e a razão pela qual eu vivo. Cada dia ao seu lado é uma dádiva que aprecio com todo o meu coração. Seu amor me dá força, coragem e propósito. Com você, tudo faz sentido e cada desafio se torna mais fácil de enfrentar. Seu carinho e apoio me fazem sentir invencível. Não consigo imaginar um futuro sem você, pois você é a luz que ilumina meu caminho e a felicidade que preenche meus dias. Maria, você é minha vida, meu amor e minha maior bênção.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Meu Destino de Amor', description: 'Maria, desde o momento em que te conheci, soube que nosso encontro era destino. Nosso amor foi escrito nas estrelas e selado pelo universo. Cada dia ao seu lado confirma que fomos feitos um para o outro. Seu amor é o meu norte, guiando-me através dos desafios e celebrando comigo cada vitória. Você é a razão pela qual acredito em almas gêmeas e no poder do amor verdadeiro. Não há dúvida em meu coração de que nosso destino é estar juntos para sempre. Maria, você é meu destino de amor, e estou eternamente grato por isso.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Luz do Meu Caminho: Maria', description: 'Maria, você é a luz que guia meu caminho, iluminando minha vida com seu amor e sua sabedoria. Seu sorriso é um farol que me orienta nos momentos mais sombrios e me dá esperança quando tudo parece perdido. Cada palavra sua é um conselho que levo a sério e que me ajuda a tomar as melhores decisões. Você traz clareza e propósito aos meus dias, fazendo-me sentir mais seguro e confiante. Com você ao meu lado, sinto que posso enfrentar qualquer desafio. Maria, você é minha guia, minha inspiração e a luz do meu caminho. Te amo com todo meu coração.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Razão de Viver', description: 'Maria, você é a razão pela qual acordo todos os dias com um sorriso no rosto e um coração cheio de esperança. Seu amor dá sentido à minha existência e me faz querer ser uma pessoa melhor. Cada momento ao seu lado é uma bênção que valorizo profundamente. Você trouxe alegria, paz e propósito à minha vida de uma maneira que nunca imaginei ser possível. Sem você, minha vida seria incompleta e sem direção. Maria, você é minha razão de viver, meu amor e minha maior felicidade. Amo você mais do que palavras podem expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Amor Imortal por Maria', description: 'Maria, nosso amor é imortal, destinado a durar além do tempo e do espaço. Desde o momento em que nos encontramos, senti que nossa conexão era única e eterna. Seu amor trouxe uma nova dimensão à minha vida, algo que nunca pensei ser possível. Juntos, enfrentamos desafios e celebramos vitórias, sempre com a certeza de que nosso amor é indestrutível. Cada dia ao seu lado confirma que fomos feitos um para o outro, e que nosso amor é verdadeiramente eterno. Maria, meu amor por você é imortal, e sempre será assim.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Você é Minha Esperança', description: 'Maria, você trouxe esperança à minha vida de uma maneira que eu nunca imaginei ser possível. Seu amor me dá forças para enfrentar qualquer desafio e acreditar em um futuro melhor. Quando tudo parece incerto, você é a certeza que me mantém firme. Sua presença é um farol de luz que ilumina meus dias mais sombrios e me dá coragem para seguir em frente. Com você, sinto que tudo é possível e que o amor pode superar qualquer obstáculo. Maria, você é minha esperança, minha força e meu amor eterno. Amo você com todo meu ser.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Cada Momento com Você, Maria', description: 'Maria, cada momento ao seu lado é uma lembrança preciosa que guardo no coração. Desde os momentos mais simples até os mais grandiosos, você transforma tudo em algo especial e inesquecível. Seu amor, sua alegria e sua presença trazem uma magia única a cada segundo que passamos juntos. Com você, aprendi a valorizar cada instante e a viver plenamente. Cada sorriso, cada toque, cada palavra sua é um presente que aprecio profundamente. Maria, cada momento com você é um tesouro que guardo com todo o carinho. Amo você mais do que tudo.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Companheira de Alma', description: 'Maria, você é minha companheira de alma, a pessoa com quem compartilho meus sonhos, medos e esperanças. Desde o momento em que nos conhecemos, senti uma conexão profunda que só se fortalece com o tempo. Seu amor, sua compreensão e sua lealdade são a base do nosso relacionamento. Juntos, enfrentamos desafios e celebramos vitórias, sempre com a certeza de que podemos contar um com o outro. Você é minha amiga, minha confidente e minha parceira para a vida toda. Maria, minha alma encontrou a sua, e sou eternamente grato por isso.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Meu Mundo é Você, Maria', description: 'Maria, você é o centro do meu mundo e a razão pela qual tudo faz sentido. Cada pensamento, cada decisão e cada sonho inclui você, pois sem você nada teria o mesmo valor. Seu amor é o que dá cor e vida aos meus dias, transformando a rotina em algo extraordinário. Com você, sinto que meu mundo é completo e cheio de possibilidades. Você trouxe uma alegria e uma paz que nunca pensei ser possíveis. Maria, meu mundo gira ao seu redor, e sou eternamente grato por ter você na minha vida. Amo você com todo meu coração.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Graça de Amar Maria', description: 'Maria, amar você é uma experiência repleta de graça e beleza. Seu amor trouxe uma luz especial à minha vida, iluminando até os momentos mais sombrios. Com você, aprendi a ver o mundo de uma maneira mais positiva e cheia de esperança. Seu carinho, sua paciência e sua compreensão são dons que valorizo profundamente. Cada dia ao seu lado é uma nova oportunidade de apreciar a beleza do nosso amor. Maria, você é uma bênção que trouxe graça e harmonia à minha vida. Amo você mais do que palavras podem expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Serenidade', description: 'Maria, sua presença traz uma serenidade indescritível ao meu coração. Quando estou ao seu lado, sinto uma paz profunda que acalma minha mente e alma. Seu amor é um refúgio seguro onde encontro conforto e segurança. Cada momento com você é um lembrete de que tudo ficará bem, não importa o que aconteça. Sua sabedoria e sua paciência me inspiram a ser uma pessoa melhor e a enfrentar os desafios com mais calma. Maria, você é minha serenidade, meu porto seguro e o amor da minha vida. Amo você com todo meu ser.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Seu Amor Me Completa, Maria', description: 'Maria, seu amor trouxe uma completude à minha vida que nunca imaginei ser possível. Antes de você, havia um vazio que eu não sabia como preencher. Agora, sinto que minha vida é plena e realizada graças a você. Seu carinho, sua compreensão e sua dedicação são tudo o que eu preciso para ser feliz. Com você, encontrei a parte que faltava em mim e a felicidade que sempre procurei. Seu amor me completa de uma maneira que nada mais poderia. Maria, você é minha outra metade, meu amor e minha felicidade completa.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Para Maria, com Todo Meu Amor', description: 'Maria, este é um pequeno gesto para expressar todo o meu amor por você. Desde o momento em que te conheci, soube que você era a pessoa com quem queria passar o resto da minha vida. Seu amor trouxe uma alegria indescritível à minha vida e me fez acreditar no poder do amor verdadeiro. Cada dia ao seu lado é uma bênção que aprecio profundamente. Quero que saiba que você é minha maior prioridade e que farei tudo para proteger e fortalecer nosso amor. Para você, Maria, com todo meu amor, dedico minha vida e meu coração.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Doce Metade', description: 'Maria, você é minha doce metade, a pessoa que completa minha alma e meu coração. Desde que te conheci, senti que minha vida estava finalmente completa. Seu amor trouxe um equilíbrio e uma harmonia que eu nunca havia experimentado. Juntos, somos mais fortes e capazes de enfrentar qualquer desafio. Seu carinho, sua compreensão e sua lealdade são a base do nosso relacionamento. Amo cada parte de você e sou eternamente grato por ter encontrado minha outra metade. Maria, você é minha doce metade e meu amor eterno.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Meu Coração Pertence a Maria', description: 'Maria, desde o momento em que te conheci, soube que meu coração pertencia a você. Seu amor é a força que guia minhas ações e dá sentido à minha vida. Cada batida do meu coração é um lembrete constante de quanto te amo. Você trouxe uma alegria indescritível à minha vida e me fez acreditar no poder do amor verdadeiro. Não há nada que eu não faria por você, pois meu coração é totalmente seu. Maria, você é minha alma gêmea, meu amor e a dona do meu coração para sempre.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Você é Meu Sonho Realizado', description: 'Maria, você é a personificação de todos os meus sonhos e desejos. Desde que te conheci, senti que minha vida finalmente fazia sentido. Seu amor trouxe uma felicidade que eu nunca havia experimentado. Cada momento ao seu lado é uma realização de tudo o que sempre sonhei. Com você, encontrei a paz, a alegria e o amor verdadeiro. Você é a realização de cada esperança e desejo que tive. Maria, você é meu sonho realizado, minha felicidade e meu amor eterno. Amo você mais do que palavras podem expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'O Meu Tudo é Você, Maria', description: 'Maria, você é tudo para mim. Desde o momento em que te conheci, minha vida ganhou um novo significado. Seu amor é a força que me impulsiona a ser uma pessoa melhor e a enfrentar cada dia com mais coragem. Você é minha melhor amiga, minha confidente e minha eterna companheira. Não consigo imaginar minha vida sem você, pois você é a razão pela qual eu existo. Cada momento ao seu lado é uma bênção que aprecio profundamente. Maria, você é meu tudo, meu amor e minha maior felicidade.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Razão de Existir', description: 'Maria, você é a razão pela qual eu acordo todos os dias com um sorriso no rosto e um coração cheio de esperança. Seu amor dá sentido à minha existência e me faz querer ser uma pessoa melhor. Cada momento ao seu lado é uma bênção que valorizo profundamente. Você trouxe alegria, paz e propósito à minha vida de uma maneira que nunca imaginei ser possível. Sem você, minha vida seria incompleta e sem direção. Maria, você é minha razão de existir, meu amor e minha maior felicidade. Amo você mais do que palavras podem expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Força do Meu Amor: Maria', description: 'Maria, a força do meu amor por você é algo que nunca imaginei ser possível. Desde o momento em que te conheci, senti que nosso amor era inquebrável. Cada dia ao seu lado confirma que fomos feitos um para o outro e que nosso amor é indestrutível. Enfrentamos desafios e celebramos vitórias, sempre com a certeza de que podemos contar um com o outro. Seu amor é a base de tudo o que sou e a razão pela qual acredito no poder do amor verdadeiro. Maria, a força do meu amor por você é imensa e eterna. Amo você com todo meu coração.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Doce Tentação', description: 'Maria, você é a doce tentação que trouxe uma nova dimensão à minha vida. Seu amor é irresistível e sua presença, uma constante fonte de alegria e desejo. Cada momento ao seu lado é uma tentação que não consigo resistir. Seu sorriso, seu toque e suas palavras me encantam de uma maneira única. Com você, aprendi a valorizar cada instante e a viver plenamente. Você é a tentação que dá sabor à minha vida e a razão pela qual sou tão feliz. Maria, você é minha doce tentação e meu amor eterno.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Você é Meu Universo, Maria', description: 'Maria, você é o centro do meu universo e a razão pela qual tudo faz sentido. Cada pensamento, cada decisão e cada sonho inclui você, pois sem você nada teria o mesmo valor. Seu amor é o que dá cor e vida aos meus dias, transformando a rotina em algo extraordinário. Com você, sinto que meu universo é completo e cheio de possibilidades. Você trouxe uma alegria e uma paz que nunca pensei ser possíveis. Maria, meu universo gira ao seu redor, e sou eternamente grato por ter você na minha vida. Amo você com todo meu coração.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Pura Felicidade', description: 'Maria, você trouxe uma felicidade pura e verdadeira à minha vida. Desde o momento em que te conheci, senti que tudo fazia sentido. Seu amor é a fonte de toda a minha alegria e paz. Cada dia ao seu lado é uma bênção que aprecio profundamente. Você trouxe luz e esperança aos meus dias de uma maneira que nunca imaginei ser possível. Com você, sinto que posso enfrentar qualquer desafio e alcançar qualquer sonho. Maria, você é minha pura felicidade, meu amor e minha maior bênção. Amo você mais do que palavras podem expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Magia de Estar com Maria', description: 'Maria, estar com você é como viver em um conto de fadas cheio de magia e encantamento. Cada momento ao seu lado é uma nova aventura que me enche de alegria e esperança. Seu amor transforma a rotina em algo extraordinário e cada dia em uma celebração da vida. Com você, sinto que tudo é possível e que o amor pode superar qualquer obstáculo. Sua presença traz uma magia única à minha vida, algo que nunca pensei ser possível. Maria, a magia de estar com você é algo que aprecio profundamente. Amo você com todo meu ser.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Maria, Minha Fonte de Inspiração', description: 'Maria, você é a fonte de toda a minha inspiração. Seu amor, sua beleza e sua sabedoria me motivam a ser uma pessoa melhor a cada dia. Cada momento ao seu lado é uma oportunidade de aprender e crescer. Seu carinho e sua compreensão são a base de tudo o que sou e tudo o que espero ser. Com você, sinto que posso alcançar qualquer objetivo e realizar qualquer sonho. Você trouxe uma nova dimensão à minha vida, algo que nunca imaginei ser possível. Maria, você é minha fonte de inspiração e meu amor eterno. Amo você mais do que palavras podem expressar.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'A Beleza do Amor de Maria', description: 'Maria, a beleza do seu amor trouxe uma nova luz à minha vida. Desde o momento em que te conheci, senti que tudo fazia sentido. Seu amor é a razão pela qual acordo todos os dias com um sorriso no rosto e um coração cheio de esperança. Cada momento ao seu lado é uma bênção que aprecio profundamente. Você trouxe uma alegria e uma paz que nunca pensei ser possíveis. Com você, sinto que posso enfrentar qualquer desafio e alcançar qualquer sonho. Maria, a beleza do seu amor é algo que aprecio profundamente. Amo você com todo meu ser.'));
  SqfliteData().insertData(MessageModel(id: const Uuid().v1(), message: 'Para Sempre Com Você, Maria', description: 'Maria, desde o momento em que te conheci, soube que queria passar o resto da minha vida ao seu lado. Seu amor trouxe uma alegria indescritível à minha vida e me fez acreditar no poder do amor verdadeiro. Cada dia ao seu lado é uma nova oportunidade de apreciar a beleza do nosso amor. Quero que saiba que você é minha maior prioridade e que farei tudo para proteger e fortalecer nosso amor. Para você, Maria, com todo meu amor, dedico minha vida e meu coração. Para sempre com você, Maria, é a única realidade que desejo. Amo você eternamente.'));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => MessageBloc(GetIt.instance.get<SqfliteData>()),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Flutter Demo',
        theme: const MaterialTheme(TextTheme()).dark(),
        home: MyPageView(),
      ),
    );
  }
}
